# Generated by Django 5.0.3 on 2024-04-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminVisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
