# Generated by Django 4.2.11 on 2024-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_adminvisitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminVisitCount',
        ),
    ]
