# Generated by Django 4.2.11 on 2024-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_delete_adminvisitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
